POST http://localhost:3001/api/probes
Content-Type: application/json

{
    "_id": "GP00099",
    "lot": "VVX24",
    "manufactureDate": "03/01/2020",
    "certificationDate": "03/02/2020",
    "expirationDate": "03/02/2022"
}

###
GET http://localhost:3001/api/probes

###
DELETE http://localhost:3001/api/probes/G10000

###
PUT http://localhost:3001/api/probes/GP00007
Content-Type: application/json

{
    "certificationDate": "03/02/2024",
    "expirationDate": "03/02/2026"
}